@startuml
 
New --> NewCopyAndInsert: 临时对象

New: 具有ID的对象是游离对象

NewCopyAndInsert: 创建新对象，COPY临时对象属性
NewCopyAndInsert: 并持久化此对象，计划执行一条Inert语句

NewCopyAndInsert --> ReturnNews: 返回插入的持久化新对象

New --> 查看em缓存中是否存在: 游离对象
查看em缓存中是否存在 --> CopyAndUpdate: 存在
CopyAndUpdate: 将游离对象的属性copy到em缓存中的对象中
CopyAndUpdate: 并计划执行一条update语句

CopyAndUpdate --> ReturnNews:返回更新的持久化数据


查看em缓存中是否存在 --> 查看数据库中是否存在: 不存在

查看数据库中是否存在 --> LoadAndUpdate: 存在


LoadAndUpdate: 从数据库中load对应的对象
LoadAndUpdate: copy游离对象的属性到Load对象
LoadAndUpdate: 并计划执行一条udpate语句

LoadAndUpdate --> ReturnNews: 返回更新的持久化数据

查看数据库中是否存在 --> NewCopyAndInsert: 不存在 

 

@enduml